### ISSUE TITLE
I have Asus USB-AC68 with rtl8814au and injection NOT WORKING!!

### ISSUE THREAD

**Issue by ghost** [n0ss/realtek-rtl88xxau-dkms#1] opened 2020-11-26 03:53 UTC
At first I was happay to fine your driver, But i find that its not workinging for me(5.9.0-kali2-amd64)

**Comment by n0ss** [comment] 2020-11-26 16:43
Hi. I was having troubles with Kali as well actually ! On the kernel 5.9.0. But just so you know this is a package from Kali.
I guess the problem is in Kali rolling system.

Could you try something (I did the trick for me) try to flash Parrot OS Security on a USB ? Boot on ParrotOS.

Then try : "hcxdumptool -i wlan0 --check_driver" then do "hcxdumptool -i wlan0 --check_injection"

This way, you will confirm that this issue is related to the driver and not your Kali system. (personnaly, I've had lots of issues with Kali, less with Parrot, but my main system is on Ubuntu, much more stable and every tools I need for pentesting can be installed)

EDIT : Also just to be sure, I'm assuming that you are running Kali installation, not a live USB. Can you confirm this ?
This is the funniest part, I have noticed that this package (from Kali repos) does NOT work on the latest updates of Kali, due to its rolling state, something broke at some point. This is why I want to check your ASUS device in a live ParrotOS environment, which I can confirm (I checked yesterday) is running out of the box AWUS1900 (RTL8814AU).

**Comment by ghost** [comment] 2020-11-26 16:56
> Hi. I was having troubles with Kali as well actually ! On the kernel 5.9.0. But just so you know this is a package from Kali.
> I guess the problem is in Kali rolling system.
> 
> Could you try something (I did the trick for me) try to flash Parrot OS Security on a USB ? Boot on ParrotOS.
> 
> Then try : "hcxdumptool -i wlan0 --check_driver" then do "hcxdumptool -i wlan0 --check_injection"
> 
> This way, you will confirm that this issue is related to the driver and not your Kali system. (personnaly, I've had lots of issues with Kali, less with Parrot, but my main system is on Ubuntu, much more stable and every tools I need for pentesting can be installed)

Can you tell me in which operating system it works for you?

**Comment by n0ss** [comment] 2020-11-26 17:03
Well it works perfectly in live Parrot OS, installed&updated Parrot OS, Ubuntu (and all stable debian-based), does NOT work in latest installed Kali but I have not checked with LIVE Kali from official site.

That is why I'm suggesting you check this out (I do not have ASUS USB-AC68 here) : https://parrotlinux.org/download/
This is another Kali-like distro (more tools actually). I use hcxdumptools (integrated test for driver and injection)

I'm asking you this because the driver in the distro is the same as here. If you can confirm that Parrot works, then you know that your problem is coming from Kali. (also check my edit are running Live or installed&upgraded ?)

Also, are you using Kali 2020.3 or 2020.4 ?

**Comment by ghost** [comment] 2020-11-26 21:11
> Well it works perfectly in live Parrot OS, installed&updated Parrot OS, Ubuntu (and all stable debian-based), does NOT work in latest installed Kali but I have not checked with LIVE Kali from official site.
> 
> That is why I'm suggesting you check this out (I do not have ASUS USB-AC68 here) : https://parrotlinux.org/download/
> This is another Kali-like distro (more tools actually). I use hcxdumptools (integrated test for driver and injection)
> 
> I'm asking you this because the driver in the distro is the same as here. If you can confirm that Parrot works, then you know that your problem is coming from Kali. (also check my edit are running Live or installed&upgraded ?)
> 
> Also, are you using Kali 2020.3 or 2020.4 ?

I try Parrot and Ubuntu , both of them airmon-ng start .. stuck 
![image](https://user-images.githubusercontent.com/74883057/100391220-6f184f80-303b-11eb-84e1-ae2894aa07e5.png)

And when I tried to do it manually as you suggested it does put it in Monitor mode but airodump-ng not working 
![image](https://user-images.githubusercontent.com/74883057/100391637-b6531000-303c-11eb-8215-8316ee3e99dd.png)

**Comment by n0ss** [comment] 2020-11-27 09:53
OK. You NEED to do this everytime you intend to monitor/inject
`airmon-ng check kill`

Check your image. WPA-supplicant and NetworkManager are conflicting with the aircrack suite/hcxdumptool.

So the process is simple : 
`airmon-ng check kill`
`hcxdumptool -i wlx******* --check_driver`
`hcxdumptool -i wlx******* --check_injection`

Maybe do this in ParrotOS (Ubuntu works as well but you won't need to install anything)
ALSO, if you do this in ParrotOS, don't do a full upgrade, just check with the live session, I mean this for troubleshooting reasons.

Could you put the output of those 3 commands here please ?

**Comment by ghost** [comment] 2020-11-27 17:46
This is what i get:
![image](https://user-images.githubusercontent.com/74883057/100473640-7f860400-30e7-11eb-9a98-ff6ae72da7dc.png)

AND ITS WORRKING!!!

**EDIT:** but airmon-ng DONT put it in monitor mode!! I use airodum-ng as usual and this is what get the card into monitor mode. If use airmone-ng start wlan0 like always its stuck as i posted before.

one bug its that:
![image](https://user-images.githubusercontent.com/74883057/100474274-f53e9f80-30e8-11eb-9d65-5ecd80e9d30d.png)
but its actually send DeAuth!!!

ALSO i found that wifi.recon on bettercap not working something to do with txpower
![image](https://user-images.githubusercontent.com/74883057/100475086-e2c56580-30ea-11eb-893f-c7adf90a49d5.png)


THANK YOU SO SO MUCH!!!

**Comment by n0ss** [comment] 2021-02-15 15:59
Could you close the issue please ?

**Closed as completed by n0ss** 2021-02-15 15:59 UTC
